### ISSUE TITLE
Iteration

### ISSUE THREAD

**Issue by jomala** [magiclen/enum-ordinalize#2]
This is really useful - thank you.

I wonder though if your documentation could pull out a few more features. For instance, if you accept the default ordinalization (from zero up, contiguous) then you can iterate through all variants in order using
```
(0..)
    .map(|i| Unit::from_ordinal(i))
    .take_while(|u| u.is_some())
    .filter_map(|u| u)
```
and count how many variants there are by appending
```
    .count()
```

**Comment by magiclen** [comment]
The performance of your code example would not be good. The way to count the variants should be reasonably done in O(1).

I'm considering rewriting this crate using proc macros instead of the `create_ordinalized_enum!` declarative macro so that I can also solve your other issue #3 and make this crate easier to use.

**Comment by jomala** [comment]
Okay. Performance is not my focus, so O(N) is fine. I really appreciate what this crate does already, but any improvements you can make will be very welcome too.

**Comment by magiclen** [comment]
@jomala Hi, I've reimplemented this crate using proc macros.

The variants (in an array) can be got by calling the `variants` associated function. If you just need the count, using the `variant_count` associated function instead.

**Comment by jmlMetaswitch** [comment]
Thank you - this is very neat now.

However, Ord and PartialOrd don't seem to be implemented by default, and I can't derive them either. I can implement them manualy easily enough, but is it possible to include them when you derive(Ordinalize)?

**Comment by magiclen** [comment]
I'm still thinking whether `Debug`, `Ord`, `PartialOrd`, `Eq`, `PartialEq`,  `Copy`, `Clone` traits should be added by this crate or not because it is not every case that needs all of them. Moreover, writing/typing the trait names in the `derive` attribute is convenient enough.

By the way, `3.1.0` has been released. It can handle more complicate cases such as,

```rust
const FOUR: i8 = 4;

const fn eight() -> i8 {
    8
}

const TEN: i16 = 10;

#[derive(Debug, PartialEq, Eq, Ordinalize)]
#[repr(i8)]
enum MyEnum {
    Zero,
    One,
    Two = 0 + 2,
    Three,
    Four,
    Six = FOUR + 2,
    Seven,
    Eight,
    Ten = TEN as i8,
    Eleven,
    Twelve,
    Hundred = 100,
    HundredOne,
    HundredTwo,
}
```

**Comment by magiclen** [comment]
@jmlMetaswitch Could you give me  several examples that built-in traits cannot be implemented for via the `derive` attribute?

**Comment by jomala** [comment]
My mistake. I tried to derive `Ord` without `PartialOrd`. It's working perfectly for me now.

Thank you for all your work on this!
